[variables]
NODE_VERSION = "20"
NPM_CONFIG_PRODUCTION = "false"

[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = [
  "npm ci --include=dev"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"

[staticAssets]
# Enable static asset serving for Next.js
"public" = "/"
".next/static" = "/_next/static"
